config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'pages#home'
  get 'lobby', to: 'pages#lobby'
  get 'tour', to: 'pages#tour'
  resources :games, only: [:new, :create, :show, :destroy] do
    resources :comments, only: [:create]
  end
  resources :pieces, only: [:update]
end

app/views/pages/home.html.erb
<div class="container">
  <div class="box text-center col-8">
    <h3><%= link_to 'Info page. Does not require signing in.', tour_path, class: "green" %></h3>
    <br/>
    <% if current_user %>
      <h3><%= link_to "Host a match", new_game_path, class: "green" %></h3>
      <br/>
      <h3><%= link_to "Go to lobby", lobby_path, class: "green" %></h3>
      <br/>
      <h3><%= link_to 'Log out', destroy_user_session_path, method: :delete, class: "green" %></h3>
    <% else %>
      <h3><%= link_to "Log in", new_user_session_path, class: "green" %></h3>
      <br/>
      <h3><%= link_to "Sign up", new_user_registration_path, class: "green" %></h3>
    <% end %> 
  </div>
</div>

app/views/pages/lobby.html.erb
<div class="green page-content">
  <h3>Lobby</h3>

  <br/><br/>

  <%= react_component("Lobby", games: @games, root_url: root_url) %>

</div>

app/views/pages/tour.html.erb
<div class="green page-content col-8">
  <h1>Hello and welcome to my chess app!</h1>
  <br/>
  <h3>
    Here I want to provide a tour of this app and give a bird's eye
    view of how it works along with some information about myself.
  </h3>
  <br/><br/>
  <h2>About me</h2>
  <br/>
  <h4>
    I origionally graduated from a bootcamp that taught Ruby on Rails.
    Since I graduated I've continued learning and imporving my programming
    skills. I've also made open source contributions to both the Ruby for
    Good Casa and Human Essentials applications.
    <br/><br/>
    So about this chess app. It's the result of a large amount of self
    learning. For example when I graduated I had never heard of websocket
    protocal which this project uses for its real time functionality.
    I had to do quite a bit of reaearch to learn how to set this up
    with rails. Also I had to do a good deal of practice/research with
    React for the piece movement and chat.
    <br/><br/>
    Since I completed this project, I've continued programming which resulted
    in me gaining more skill so I recently did some refactoring for the backend.
    I gained an appreciation for the Rubocop gem when I made the before
    mentioned open source contributions to the Ruby for Good applications, so
    I added it to this project. I removed redundant self statements, made the
    code more declarative, and got far more comfortable letting the tests
    that I wrote guide me in the refactor process.
    <%= link_to "Here's", "https://github.com/Learningstuff98/chess/pull/26/files" %>
    a merged pull request from the refactor.
    <br/><br/>
    In September of 2023 I merged a PR that moved the logic responsible for
    piece movement and detecting any pieces that are blocking a given path
    into their own modules for the sake of learning and maintainability.
    This was the first time that I've used modules with rails.
    <%= link_to "Here's the PR.", "https://github.com/Learningstuff98/chess/pull/29/files" %> 
    <br/><br/>
    In October of 2023 I merged a PR that adds event messages that render in
    real time above the board. These messages describe game events like piece movement,
    piece capturing and if an illegal jump over is attempted.
    <%= link_to "Here's the PR.", "https://github.com/Learningstuff98/chess/pull/30/files" %> 
    <br/><br/>
    Currently I'm working as a seafood deli clerk. It's a job that requires
    teamwork and invloves a high degree of human interaction, but I'm
    looking for work in the tech industry because creating software is
    what I'm passionate about. I'm proactive and very willing to learn.
  </h4>
  <br/><br/>
  <h2>Overview</h2>
  <br/>
  <h4>
    This is a rails 6 app that uses devise for user functionality.
    Users can start games and choose which color that they want to
    play as, or they can join games in the lobby that are being
    hosted by other users. The rules of chess are enforced on the
    back end. The game is turn based, pieces can't jump over
    eachother except for knights and a victor can be declared.
  </h4>

  <br/><br/>
  <%= image_tag 'updatedchess.gif', class: 'container gif-box' %>
  <br/><br/>
  <h4>A real time chat box is included below the board.</h4>
  <br/><br/>
  <%= image_tag 'chat.gif', class: 'container gif-box' %>
  <br/><br/>
  <h4>Pawns can be promoted to either rooks, knights, bishops, or queens.</h4>
  <br/>
  <%= image_tag 'pawnpromotionupdated.gif', class: 'container gif-box' %>
  <br/><br/>

  <h2>Back end</h2>
  <br/>
  <h4>
    Games belong to users. Pieces and comments belong to games.
    Games contain functionality for things like creating the pieces
    with their starting positions and determining the victor.
    Pieces call on modules which contain logic for things like how a piece is
    allowed to move and whether or not another piece is in the way.
  </h4>
  <br/>
  <h4>
    When a piece is selected and a tile is clicked, this sends a patch
    request to the back end. Pieces have x and y attributes along with
    destination_x and destination_y attributes. The logic around piece
    movement is based on the starting point (x and y attributes) and
    the proposed destination (destination_x and destination_y attributes).
    If a proposed move is legal then the x and y attributes are updated
    and a broadcast is sent with action cable to the front end with the
    game and its pieces.
  </h4>
  <br/>
  <h4>
    This project uses both Rspec and Factorybot for testing. I have tests
    written for models, modules and controllers, github links provided below:
    <br/><br/>
    <%= link_to "request tests", 'https://github.com/Learningstuff98/chess/tree/master/spec/requests' %>
    <br/>
    <%= link_to "model tests", 'https://github.com/Learningstuff98/chess/tree/master/spec/models' %>
    <br/>
    <%= link_to "module tests", 'https://github.com/Learningstuff98/chess/tree/master/spec/helpers' %>
  </h4>
  <br/>
  <h2>Front end</h2>
  <br/>
  <h4>
    This app uses out of the box rails html.erb views along with React.js
    when necessary thanks to the react rails gem. The chess board, chat and
    the lobby all use react along with action cable to function. When a
    broadcast from the back end is recieved, the data is then loaded into
    state.

    <br/><br/>
    <%= image_tag 'updatedlobbygif.gif', class: 'container gif-box' %>
    <br/><br/>

    The chess board and chat box work for different screen sizes, shown
    below.

    <br/><br/>
    <%= image_tag 'updateddynamicformattedchess.gif', class: 'container gif-box' %>
    <br/><br/>
  </h4>
  <h2>What I would do differently</h2>
  <br/>
  <h4>
    I would break the piece model up into seperate models like rook, queen,
    pawn ect. I would move logic that would need to be shared by some of the
    models like rooks and queens to their own modules.
  </h4>
</div>

<br/><br/><br/><br/>